# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push
  # branches:
  #   - main
  # pull_request:
  #   branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: NPM Install
        run: npm install
      - name: React Build
        run: npm run build
      - name: zip build resulit
        run: tar -czvf build.tar.gz public
      - name: archive zip
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar.gz
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: extract build
        run: tar -xzvf build.tar.gz
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      # Sync the files from public folder to the kleeut.com bucket
      - name: Deploy to S3
        run: aws s3 sync ./public s3://jacks-hackathon-auth0-actions --acl public-read
