name: build

steps:
  - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - uses: actions/setup-node@v2-beta
    with:
      node-version: "12"

- name: NPM Install
  run: npm install
- name: Run Build
  run: npm run build