deploy:
  needs:
    - build

- name: download artifact
  uses: actions/download-artifact@v2
  with:
    name: build
- name: extract build
  run: tar -xzvf build.tar.gz

- name: Set AWS credentials
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

- name: Deploy to S3
  run: aws s3 sync ./public s3://kleeut.com --acl public-read